signin:
    image: hackday/signin
    ports:
        - "8080:8080"
    links:
        - rabbitmq
        - confgiserver

signup:
    image: hackday/signup
    ports:
        - "8081:8080"
    links:
        - rabbitmq
        - confgiserver

servicesignup:
    image: hackday/servicesignup
    ports:
        - "8082:8080"
    links:
        - rabbitmq
        - confgiserver

resetpassword:
    image: hackday/resetpassword
    ports:
        - "8083:8080"
    links:
        - rabbitmq
        - confgiserver

forgotusername:
    image: hackday/forgotusername
    ports:
        - "8084:8080"
    links:
        - rabbitmq
        - confgiserver

captcha:
    image: hackday/captcha
    ports:
        - "8085:8080"
    links:
        - rabbitmq
        - confgiserver

navigation:
    image: hackday/navigation
    ports:
        - "8086:8080"
    links:
        - rabbitmq
        - confgiserver

express:
    image: hackday/express
    ports:
        - "8087:8080"
    links:
        - rabbitmq
        - confgiserver

confgiserver:
    image: hackday/configserver
    ports:
        - "8888:8888"
    links:
        - rabbitmq

rabbitmq:
    image: rabbitmq
    expose:
        - "5672"
